import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { IMatch } from "../../models/Match";
import { useEffect, useState } from "react";

import ChessUser, { IUser } from "../../models/User";

import Modal from "react-bootstrap/Modal";
import Button from "react-bootstrap/Button";
import Computer from "../../components/Computer/Computer";

/**
 * States of play. Used to decide what to render.
 */
enum ANALYZE_STATES {
  INIT, // the user is not in a match and is not waiting for one
  ANALYSIS, // the user is in a match & is playing
  END, // the user has just ended a match (won, lost or drew)
}

const Home: NextPage = () => {
  return (
    <div className="row">
      <div className="col-12">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* <Modal
                    show={state.puzzle_state === PUZZLE_STATES.PUZZLE_END}
                    onHide={handleClose}
                >
                    <Modal.Header closeButton>
                        <Modal.Title>Puzzle complete!</Modal.Title>
                    </Modal.Header>
                    <Modal.Body>Congratulations!! You've solved the puzzle!</Modal.Body>
                    <Modal.Footer>
                        <Button variant="primary" onClick={handleClose}>
                            Next Puzzle
                        </Button>
                    </Modal.Footer>
                </Modal> */}

        <main className="container d-flex flex-col justify-content-center align-items-center">
          {/* <div>Match: {state.matchId}</div> */}

          <h1 className="display-2">Computer</h1>

          <p className="lead">Try your hand at Stockfish!</p>

          <Computer elo={1350} />
        </main>
      </div>
    </div>
  );
};

export async function getStaticProps() {
  return {
    props: {
      protected: true,
    },
  };
}

export default Home;
